version: '3.8'

services:
  tetris-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_API_BASE_URL=http://localhost:3003
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - tetris-server

  tetris-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    working_dir: /app/server
    user: node
    ports:
      - "3003:3003"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
      - ./server/data:/app/server/data:delegated
    environment:
      - NODE_ENV=development
      - PORT=3003
    command: npm start
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3003/leaderboard"]
      interval: 30s
      timeout: 10s
      retries: 3