version: '3.8'

services:
  tetris-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - tetris-server

  tetris-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    user: node
    ports:
      - "3003:3003"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/data:/app/data:rw
    environment:
      - NODE_ENV=development
      - PORT=3003
    command: npm run dev