version: '3.8'

services:
  tetris-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0
    stdin_open: true
    tty: true