version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://194.233.80.15:3003
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./server:/app
      - /app/node_modules
      - sqlite_data:/app/data
    environment:
      - PORT=3003

volumes:
  sqlite_data:
