version: '3.8'

services:
  tetris-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://194.233.80.15:3003
      - VITE_WS_URL=ws://194.233.80.15:3003
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - tetris-server

  tetris-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3003:3003"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/data:/app/data:rw
    environment:
      - NODE_ENV=development
      - PORT=3003
    user: "node"
    restart: unless-stopped