version: '3.8'

services:
  tetris-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_API_BASE_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: npm run dev -- --host 0.0.0.0
    stdin_open: true
    tty: true
    depends_on:
      - tetris-server

  tetris-server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./server/data:/app/server/data
    environment:
      - NODE_ENV=development
    command: npm start
    restart: unless-stopped