version: '3.8'

services:
  tetris-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - tetris-server

  tetris-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3003:3003"
    volumes:
      - ./server/data:/app/data:rw
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3003